name: Build wheel and release

on:
  push:
    tags:
      - "*"

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    name: Build wheel
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Build wheel
        run: poetry build
      - uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: ./dist/*.whl
  create_release:
    runs-on: ubuntu-latest
    name: Create release
    needs: [build_wheel]
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Slurm Autoscale TFE
          draft: true
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
